// START OF EXTERNAL CODE
// This code was generated by the express-generator module
// More info: https://expressjs.com/en/starter/generator.html

var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// END OF EXTERNAL CODE

// setup the layout
const expressLayouts = require('express-ejs-layouts');

app.use(expressLayouts);
app.set('layout', 'layouts/layout');

const fileUpload = require('express-fileupload');
app.use(fileUpload());

// Add bootstrap dist files as a virtual subdirectory for static files
app.use('/bootstrap', express.static(path.join(__dirname, '/node_modules/bootstrap/dist')));

require('./routes/main')(app);

// START OF EXTERNAL CODE
// This code was generated by the express-generator module
// More info: https://expressjs.com/en/starter/generator.html

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;

// END OF EXTERNAL CODE
